server:
  port: 9005
spring:
  application:
    name: zuul-getway

eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eurekaserver.com:9001/eureka
  instance:
    instance-id: zuulporxy.com
    prefer-ip-address: true

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true