server:
  port: 9900

spring:
  application:
    name: auth-server
  session:
    store-type: none
eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eurekaserver.com:9001/eureka
  instance:
    instance-id: authserver.com
    prefer-ip-address: true

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true
ouyaaa:
  security:
    oauth:
      clients[0]:
        clientId: hlxd
        clientSecret: hlxdsecret
        validitySeconds: 9000
      clients[1]:
        clientId: ouyaaa
        clientSecret: ouyaaa
        validitySeconds: 19000
        refreshSeconds: 30000000
      storeType: redis