server:
  port: 10089

eureka:
  client:
    service-url:
      defaultZone: http://edmin:edmin@eurekaserver.com:9001/eureka
  instance:
    instance-id: authclient.com
    prefer-ip-address: true

security:
  oauth2:
    client:
      client-id: ouyaaa
      client-secret: ouyaaa
      access-token-uri: http://127.0.0.1:9900/oauth/token
      user-authorization-uri: http://127.0.0.1:9900/oauth/authorize
    resource:
#      jwt:
#        key-uri: http://127.0.0.1:9900/oauth/token_key
      token-info-uri: http://localhost:9900/oauth/check_token
spring:
  application:
    name: auth-client
  security:
    user:
      name: admin
      password: 123456